import Head from 'next/head'
import {NextPage} from "next";
import Header from "../components/Header/Header"
import Hero from "../components/Hero/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Webtronics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="container">
            <Header/>
            <Hero/>
        </div>
    </>
  )
}

export default Home